DROP SCHEMA IF EXISTS teste CASCADE;
CREATE SCHEMA teste;
SET SCHEMA 'teste';

CREATE TABLE Contato_Pessoa (
	Contato INT NOT NULL,
	Doc VARCHAR(9) NOT NULL,
	PRIMARY KEY (Contato,Doc),
	FOREIGN KEY (Doc) REFERENCES Pessoa (Doc)
);

CREATE TABLE Pessoa (
	Nome VARCHAR(30) NOT NULL,
	Doc VARCHAR(9) NOT NULL UNIQUE,
	TipoDoc CHAR(2) NOT NULL,
	Sexo CHAR(1) NOT NULL,
	Idade INT NOT NULL,
	PRIMARY KEY (Doc)
);

CREATE TABLE Funcionario (
	Doc VARCHAR(9) NOT NULL UNIQUE,
	Ri INT NOT NULL,
	PRIMARY KEY (Doc),
	FOREIGN KEY (Doc) REFERENCES Pessoa (Doc)
);

CREATE TABLE Partida (
	ID INT,
	Doc VARCHAR(9),
	Numero INT NOT NULL,
	Data TIMESTAMP NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (Doc) REFERENCES Funcionario (Doc),
	FOREIGN KEY (Numero) REFERENCES Mesa (Numero)
);